### PR TITLE
Update to simple linear regression slides

### PR DESCRIPTION
**Pull request by gustavekenedi**
Minor changes to the slides. Here's a preview: https://rawcdn.githack.com/gustavekenedi/ScPoEconometrics-Slides/acdcf5453a6c2fa711ca35806955ce620aed4858/chapter_slr/chapter_slr.html

Main changes:
- drop task 2
- slide explaining what a line equation means
- change error term to residual

I'm having some issues converting to pdf despite manually increasing decktape's timeout time to 10 minutes... Not sure why. Will look into it later.

### CODE REVIEW

**Comment by floswald** [comment]
LGTM!

comments

* line refresher: consider moving the b0 tick to the y-axis instead. it may be a bit confusing to see the arrow starting from a point on the x axis (basically emphasize your dashed line - it shows b0 on the y axis)
* is the iframe running on a shinyapps app? it's a bit sluggish but it will do - probably a good idea to include it like that 
* just ping me here if that's good to go

**Comment by gustavekenedi** [comment]
Thanks I'll make the change to the line refresher. Yes the iframe is running on a shinyapps app. It's slightly sluggish I agree but still works pretty well.

**Comment by gustavekenedi** [comment]
Should be good now :)

**Comment by gustavekenedi** [comment]
Feel free to accept these PRs (this one and the tidy one) whenever you have some free time (unless you see something strange) :smile:

**Pull request merged**
