### PR TITLE
very minor change to sum data chapter

### PR DESCRIPTION
**Pull request by gustavekenedi**
Hi Florian,
Very minor change to summarising data lecture.

Important:
I had only committed the html but not all the chapter2_files in my previous PR and therefore the html slides are missing many graphs and various code outputs. Do you want me to commit so you can merge easily or do you want to knit the document on your end and then commit the new html?
Just noticed this, should have thought about it, sorry.

### CODE REVIEW

**Comment by floswald** [comment]
yes please knit the thing and include all needed files to serve the html
(pictures etc). thanks

**Comment by floswald** [comment]
i realise this is contrary to my initial instructions - sorry. I'm learning. :-)

**Comment by gustavekenedi** [comment]
no problem! done :)

**Comment by floswald** [comment]
great. to start serving the file you need to copy the url that points to the html on github (just navigate in your browser to it and copy the url of the html, and paste it into here once to cache it
https://raw.githack.com

then make sure the url on the right is linked to from our readme.

**Comment by gustavekenedi** [comment]
Ok thanks, just did it.

**Pull request merged**
