### PR TITLE
Fix iframe slr

### PR DESCRIPTION
**Pull request by gustavekenedi**
Hi @floswald,

This is a minor PR fixing the iframe issue for the interactive apps and also correcting a minor typo in the graph on line equations.

Thanks!

### CODE REVIEW

**Comment by floswald** [comment]
cool! thanks

**Comment by gustavekenedi** [comment]
my class is at 12h30, any chance you could accept the PR before then? thanks! (sorry for the last minute changes)

**Comment by floswald** [comment]
Oops sorry . It doesn’t make sense that you cannot merge the PRs given you
do all the work. I’ll change that.

**Comment by floswald** [comment]
you should have write access now which measn you can merge stuff yourself

**Pull request merged**
