### PR TITLE
Updates to lecture tidying, visualising and summarising data slides

### PR DESCRIPTION
**Pull request by gustavekenedi**
Unfortunately, it seems that my `git mv` didn't work as well as I'd have thought. You can view a preview of the updated slides here:
https://raw.githack.com/gustavekenedi/ScPoEconometrics-Slides/update_tidy/chapter_tidy/chapter_tidy.html#1

Main changes:
- quiz/recap on previous week slide
- introducing the pipe straight away and new way of presenting dplyr verbs + "better" task
- scrap base R plotting and jump straight into ggplot
- new way of presenting ggplot which is much more visual based on https://pkg.garrickadenbuie.com/gentle-ggplot2/#1
- ggplot task
- new task 4 (ScPoApps tutorial is put to do at home to avoid any issues with installing it during the lecture)
- tasks files

### CODE REVIEW

**Comment by floswald** [comment]
great!

couple things i found:

* wooclap.com link is broken
* everything else is amazing. you risk getting famous with that ggplot intro, really really well done. 👏 

do you want to fix that link and we merge or is there more coming on this?

**Comment by gustavekenedi** [comment]
Thanks for spotting the broken link! I've updated it, reknitted and redecktaped (which btw .
The ggplot intro is not at all my doing, I adapted Garrick Aden-Buie's wonderful [Gentle Guide to the Grammar of Graphics with ggplot2](https://pkg.garrickadenbuie.com/gentle-ggplot2/#1) to our data so all the merit goes to him! (I've acknowledged and linked to his presentation on slide 23 and 44.)

**Comment by gustavekenedi** [comment]
I'm just realising that the slide on correlation is a bit weak, not even mentioning that correlation is between -1 and 1. Could you please wait until I commit those changes a bit later today before pulling the PR? Thanks!

**Comment by gustavekenedi** [comment]
Note to self: publish corr_continuous app to shinyapps and embed in slide using iframe

**Comment by floswald** [comment]
(not sure why i see a second PR with the same topic? i'm waiting on this one until you say it's good)

**Comment by gustavekenedi** [comment]
Yeah saw that as well no idea why... but this one seems to be the right one. I'm waiting on decktape to produce the pdf :crossed_fingers:

**Comment by gustavekenedi** [comment]
Should be all good now :)

**Comment by floswald** [comment]
you shouldnt' worry so much about the pdf. or do you think people use them to take notes? that would be a good argument actually.

**Comment by gustavekenedi** [comment]
Yes my impression is that some students use the pdf to take notes so a priori it's probably quite important.

**Pull request merged**
