### PR TITLE
Update to intro slides

### PR DESCRIPTION
**Pull request by gustavekenedi**
Hi Florian,

I've made some changes to the intro slides. Aside from renaming the folder and files, the biggest change made is moving the class details material to the end of the lecture so that we get straight into R and doing stuff with the students and end the lecture on the mundane aspects of the class.

I've made a small stylistic change to the readme page. The syllabus now looks (or should look) like a table with links to the lecture slides as well as the task files (.Rmd and HTML).

All comments/suggestions are welcome :)

(I'm going over all the slides based on my notes when I taught last spring and on issues discussed with Pierre. I'm hoping to have updates on most lectures by the end of the week depending on how much time I can allocate to this.)

### CODE REVIEW

**Comment by floswald** [comment]
hey, sounds great! i won't have time to check all of that - just one thing - whats the thing with the js code and the countdown function?

**Comment by gustavekenedi** [comment]
[Countdown](https://github.com/gadenbuie/countdown) is a package that allows displaying a timer on a slide. Very convenient for our tasks so we can keep track of time :)
I PRed it but perhaps I can remove it for simplicity? Just tell me what you prefer

**Comment by floswald** [comment]
as long as it does not introduce some nasty dependency that does not work half of the time because of js issues in a browser, I'm fine with that. I guess you tried it out and it works?

**Comment by gustavekenedi** [comment]
I tried it out in Chrome and works like a charm!

**Comment by floswald** [comment]
Please try in Firefox and then we are good to go

**Comment by gustavekenedi** [comment]
Works on Firefox! 👍

**Pull request merged**
